"""Remove email_verification_token

Revision ID: 7e515f5cea2b
Revises: a0c1f7a893ab
Create Date: 2026-09-07 16:58:01.616285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e515f5cea2b'
down_revision = 'a0c1f7a893ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
