"""Initial schema

Revision ID: a0c1f7a893ab
Revises: 
Create Date: 2026-09-07 15:59:29.746538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c1f7a893ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_users_role_id', ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('admin_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('target_user_id', sa.String(length=36), nullable=True),
    sa.Column('target_object_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index('idx_admin_actions_action', ['action'], unique=False)
        batch_op.create_index('idx_admin_actions_admin_id', ['admin_id'], unique=False)
        batch_op.create_index('idx_admin_actions_created', ['created_at'], unique=False)
        batch_op.create_index('idx_admin_actions_target', ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('participant_one_id', sa.String(length=36), nullable=False),
    sa.Column('participant_two_id', sa.String(length=36), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_one_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_two_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_one_id', 'participant_two_id', name='uq_conversation_participants')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_conversations_participant_one', ['participant_one_id'], unique=False)
        batch_op.create_index('idx_conversations_participant_two', ['participant_two_id'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_public_id', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index('idx_institutions_country', ['country'], unique=False)
        batch_op.create_index('idx_institutions_is_verified', ['is_verified'], unique=False)
        batch_op.create_index('idx_institutions_type', ['institution_type'], unique=False)
        batch_op.create_index('idx_institutions_user_id', ['user_id'], unique=False)

    op.create_table('media_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('secure_url', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('moderation_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_uploads', schema=None) as batch_op:
        batch_op.create_index('idx_media_uploads_type', ['media_type'], unique=False)
        batch_op.create_index('idx_media_uploads_user_id', ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_created', ['created_at'], unique=False)
        batch_op.create_index('idx_notifications_is_read', ['is_read'], unique=False)
        batch_op.create_index('idx_notifications_type', ['notification_type'], unique=False)
        batch_op.create_index('idx_notifications_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('current_team', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('show_contact', sa.Boolean(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('profile_picture_public_id', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('profile_views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('idx_players_gender', ['gender'], unique=False)
        batch_op.create_index('idx_players_is_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_players_nationality', ['nationality'], unique=False)
        batch_op.create_index('idx_players_position', ['position'], unique=False)
        batch_op.create_index('idx_players_user_id', ['user_id'], unique=False)

    op.create_table('scouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scout_name', sa.String(length=255), nullable=False),
    sa.Column('scout_type', sa.String(length=50), nullable=True),
    sa.Column('agency_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('profile_picture_public_id', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.create_index('idx_scouts_country', ['country'], unique=False)
        batch_op.create_index('idx_scouts_is_verified', ['is_verified'], unique=False)
        batch_op.create_index('idx_scouts_scout_type', ['scout_type'], unique=False)
        batch_op.create_index('idx_scouts_user_id', ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_subscriptions_plan', ['plan'], unique=False)
        batch_op.create_index('idx_subscriptions_status', ['status'], unique=False)
        batch_op.create_index('idx_subscriptions_user_id', ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted_by_sender', sa.Boolean(), nullable=True),
    sa.Column('is_deleted_by_recipient', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('idx_messages_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_messages_is_read', ['is_read'], unique=False)
        batch_op.create_index('idx_messages_recipient_id', ['recipient_id'], unique=False)
        batch_op.create_index('idx_messages_sender_id', ['sender_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('mpesa_checkout_id', sa.String(length=255), nullable=True),
    sa.Column('mpesa_receipt', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True),
    sa.Column('paypal_order_id', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_payments_method', ['method'], unique=False)
        batch_op.create_index('idx_payments_status', ['status'], unique=False)
        batch_op.create_index('idx_payments_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('idx_payments_user_id', ['user_id'], unique=False)

    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizer_user_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('representative_name', sa.String(length=255), nullable=False),
    sa.Column('organization_phone', sa.String(length=30), nullable=True),
    sa.Column('organization_email', sa.String(length=255), nullable=True),
    sa.Column('representative_phone', sa.String(length=30), nullable=True),
    sa.Column('representative_email', sa.String(length=255), nullable=True),
    sa.Column('tournament_name', sa.String(length=255), nullable=False),
    sa.Column('tournament_type', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('registration_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_currency', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index('idx_tournaments_organizer', ['organizer_user_id'], unique=False)
        batch_op.create_index('idx_tournaments_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_tournaments_status', ['status'], unique=False)
        batch_op.create_index('idx_tournaments_type', ['tournament_type'], unique=False)

    op.create_table('tournament_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('registered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('participant_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('team_representative', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_participants', schema=None) as batch_op:
        batch_op.create_index('idx_tournament_participants_tournament', ['tournament_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_participants', schema=None) as batch_op:
        batch_op.drop_index('idx_tournament_participants_tournament')

    op.drop_table('tournament_participants')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index('idx_tournaments_type')
        batch_op.drop_index('idx_tournaments_status')
        batch_op.drop_index('idx_tournaments_start_date')
        batch_op.drop_index('idx_tournaments_organizer')

    op.drop_table('tournaments')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('idx_payments_user_id')
        batch_op.drop_index('idx_payments_transaction_id')
        batch_op.drop_index('idx_payments_status')
        batch_op.drop_index('idx_payments_method')

    op.drop_table('payments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_sender_id')
        batch_op.drop_index('idx_messages_recipient_id')
        batch_op.drop_index('idx_messages_is_read')
        batch_op.drop_index('idx_messages_created_at')
        batch_op.drop_index('idx_messages_conversation_id')

    op.drop_table('messages')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_subscriptions_user_id')
        batch_op.drop_index('idx_subscriptions_status')
        batch_op.drop_index('idx_subscriptions_plan')

    op.drop_table('subscriptions')
    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.drop_index('idx_scouts_user_id')
        batch_op.drop_index('idx_scouts_scout_type')
        batch_op.drop_index('idx_scouts_is_verified')
        batch_op.drop_index('idx_scouts_country')

    op.drop_table('scouts')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('idx_players_user_id')
        batch_op.drop_index('idx_players_position')
        batch_op.drop_index('idx_players_nationality')
        batch_op.drop_index('idx_players_is_featured')
        batch_op.drop_index('idx_players_gender')

    op.drop_table('players')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('idx_notifications_user_id')
        batch_op.drop_index('idx_notifications_type')
        batch_op.drop_index('idx_notifications_is_read')
        batch_op.drop_index('idx_notifications_created')

    op.drop_table('notifications')
    with op.batch_alter_table('media_uploads', schema=None) as batch_op:
        batch_op.drop_index('idx_media_uploads_user_id')
        batch_op.drop_index('idx_media_uploads_type')

    op.drop_table('media_uploads')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index('idx_institutions_user_id')
        batch_op.drop_index('idx_institutions_type')
        batch_op.drop_index('idx_institutions_is_verified')
        batch_op.drop_index('idx_institutions_country')

    op.drop_table('institutions')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_conversations_participant_two')
        batch_op.drop_index('idx_conversations_participant_one')

    op.drop_table('conversations')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_id'))
        batch_op.drop_index('idx_admin_actions_target')
        batch_op.drop_index('idx_admin_actions_created')
        batch_op.drop_index('idx_admin_actions_admin_id')
        batch_op.drop_index('idx_admin_actions_action')

    op.drop_table('admin_actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_role_id')
        batch_op.drop_index('idx_users_is_active')
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
